spring:
  application:
    name: smartpark-service

  datasource:
    url: jdbc:h2:mem:smartpark
    driver-class-name: org.h2.Driver
    username: sa #Default H2 db user and pass
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  sql:
    init:
      mode: always

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 8mR6Vn3KxQ2pZ9sLf4WcY7aHd1Jt5NxEr8Uv6BpQ
  expiration: 300000
#  expiration: 10000 # Testing Expiration

security:
  username: admin
  password: admin

logging:
  level:
    root: INFO
    com.smartpark: DEBUG

smartpark:
  auto-checkout:
    timeout-minutes: 15
    fixed-rate-ms: 60000